eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.223.58:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-zuul
zuul:
  routes:
    commmon:
      path: /common/**
      serviceId: common
