server:
  port: 8763
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 1MB
  application:
    name: common
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  datasource:
    url: jdbc:mysql://120.79.223.58:3306/test1?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Dgut240938
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: select 1
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.223.58:8761/eureka/
  instance:
    hostname: 120.79.223.58
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
    ip-address: 120.79.223.58

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    com:
      example:
        common:
          mapper: debug
