server:
  port: 8764

spring:
  application:
    name: webrtc
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
