server:
  port: 8764

spring:
  application:
    name: webrtc
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  datasource:
    url: jdbc:mysql://120.79.223.58:3306/test1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Dgut240938
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
